# Generated by Django 3.0.3 on 2020-02-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_auto_20200224_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserCenter',
        ),
        migrations.AlterModelOptions(
            name='usercenter',
            options={'verbose_name_plural': 'USERS of CENTERS'},
        ),
        migrations.CreateModel(
            name='UserBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USERS of BOCEJ-AGUIPE',
            },
        ),
    ]
