# Generated by Django 3.0.3 on 2020-02-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20200225_1116'),
        ('login', '0004_auto_20200224_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercenter',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.Center'),
        ),
    ]
