# Generated by Django 3.0.2 on 2020-03-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_usercenter_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userba',
            name='state',
        ),
        migrations.AddField(
            model_name='userba',
            name='full_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userba',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usercenter',
            name='full_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usercenter',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userba',
            name='role',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userba',
            name='type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userba',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='role',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
