# Generated by Django 3.0.3 on 2020-03-08 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center', '0004_auto_20200308_1913'),
        ('login', '0006_auto_20200304_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userba',
            name='full_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='userba',
            name='role',
            field=models.CharField(max_length=250, null=True, verbose_name='Role (admin/simple_user)'),
        ),
        migrations.AlterField(
            model_name='userba',
            name='tel',
            field=models.CharField(max_length=15, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='userba',
            name='type',
            field=models.CharField(max_length=250, null=True, verbose_name='Type (bocej/aguipe)'),
        ),
        migrations.AlterField(
            model_name='userba',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='center.Center', verbose_name='Son Centre'),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='full_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='role',
            field=models.CharField(max_length=250, null=True, verbose_name='Role (admin/simple_user)'),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='tel',
            field=models.CharField(max_length=15, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='type',
            field=models.CharField(default='center', max_length=250, null=True, verbose_name='Type (center)'),
        ),
        migrations.AlterField(
            model_name='usercenter',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
