# Generated by Django 3.0.3 on 2020-03-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200308_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='userba',
            name='email',
            field=models.CharField(max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='usercenter',
            name='email',
            field=models.CharField(max_length=250, null=True, verbose_name='Email'),
        ),
    ]
