# Generated by Django 3.0.3 on 2020-03-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200308_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userba',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usercenter',
            name='email',
        ),
    ]
