# Generated by Django 3.0.2 on 2020-02-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200, verbose_name='Nom du centre')),
                ('city', models.CharField(max_length=200, verbose_name='Ville')),
                ('date_creation', models.DateField(verbose_name='Date de creation du centre')),
                ('founder', models.CharField(max_length=200, verbose_name='Fondateur')),
                ('state', models.CharField(max_length=200, verbose_name='Etat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserProfile')),
            ],
        ),
    ]
