# Generated by Django 3.0.3 on 2020-02-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name_plural': 'CENTERS'},
        ),
        migrations.RemoveField(
            model_name='center',
            name='user',
        ),
    ]
