# Generated by Django 3.0.3 on 2020-03-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20200225_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='city',
        ),
        migrations.RemoveField(
            model_name='center',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='center',
            name='founder',
        ),
        migrations.RemoveField(
            model_name='center',
            name='state',
        ),
        migrations.AddField(
            model_name='center',
            name='c_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_email',
            field=models.CharField(max_length=200, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_state',
            field=models.CharField(max_length=200, null=True, verbose_name='Etat'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_tel',
            field=models.CharField(max_length=200, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='center',
            name='c_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom du centre'),
        ),
    ]
