# Generated by Django 3.0.3 on 2020-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20200308_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='c_name',
            new_name='c_title',
        ),
        migrations.AlterField(
            model_name='center',
            name='c_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Addresse'),
        ),
    ]
