# Generated by Django 3.0.3 on 2020-03-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20200308_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='c_tel',
            new_name='c_phone',
        ),
    ]
