# Generated by Django 3.0.3 on 2020-03-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_auto_20200308_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='c_email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='center',
            name='c_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telephone'),
        ),
    ]
